### ISSUE TITLE
Replace SHP by GeoJSON in example

### ISSUE THREAD

**Issue by FrieseWoudloper** [Appsilon/data.validator#11]
The SHP files are very big. On top of that, it's a proprietary format and kind of outdated. It's better to use GeoJSON for visualizing geospatial information in a web application. It's an open format and also much more light weight.

The SHP files contains very detailed geometry. This isn't necessary for the purposes of this example. It only has a negative impact on performance.

When www.mapshaper.org is used to simplify the geometry and save it in GeoJSON format, the geospatial data is compressed from 35 MB to approximately 1 MB. Also the HTML file containing the custom report is much smaller.

**Comment by krystian8207** [comment]
Thank you @FrieseWoudloper for solving that. Closing the issue now along with #13.
