### ISSUE TITLE
[Bug]: Accordion in `render_semantic_report_ui` does not work correctly 

### ISSUE THREAD

**Issue by SabrinaJaye** [Appsilon/data.validator#49]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

0.1.6

### Platform and OS Version

Windows 10

### What happened?

If I follow this example:
```R
library(shiny)
library(data.validator)
library(magrittr)
library(assertr)

ui <- fluidPage(
  uiOutput("validation")
)

server <- function(input, output, session) {
  report <- data_validation_report()
  validate(mtcars, name = "Verifying cars dataset") %>%
    validate_if(drat > 0, description = "Column drat has only positive values") %>%
    validate_cols(in_set(c(0, 2)), vs, am, description = "vs and am values equal 0 or 2 only") %>%
    validate_cols(within_n_sds(1), mpg, description = "mpg within 1 sds") %>%
    validate_rows(num_row_NAs, within_bounds(0, 2), vs, am, mpg, description = "not too many NAs in rows") %>%
    validate_rows(maha_dist, within_n_mads(10), everything(), description = "maha dist within 10 mads") %>%
    add_results(report)

  output$validation <- renderUI({
    render_semantic_report_ui(get_results(report))
  })
}

shinyApp(ui, server)
```

Then the accordion in the report widget is unresponsive and does not open or collapse other sections for viewing.

### Steps to reproduce

1. Copy example code into terminal
```R
library(shiny)
library(data.validator)
library(magrittr)
library(assertr)

ui <- fluidPage(
  uiOutput("validation")
)

server <- function(input, output, session) {
  report <- data_validation_report()
  validate(mtcars, name = "Verifying cars dataset") %>%
    validate_if(drat > 0, description = "Column drat has only positive values") %>%
    validate_cols(in_set(c(0, 2)), vs, am, description = "vs and am values equal 0 or 2 only") %>%
    validate_cols(within_n_sds(1), mpg, description = "mpg within 1 sds") %>%
    validate_rows(num_row_NAs, within_bounds(0, 2), vs, am, mpg, description = "not too many NAs in rows") %>%
    validate_rows(maha_dist, within_n_mads(10), everything(), description = "maha dist within 10 mads") %>%
    add_results(report)

  output$validation <- renderUI({
    render_semantic_report_ui(get_results(report))
  })
}

shinyApp(ui, server)
```
2. Try to use the accordion.

### Expected behavior

The accordion should open and close segments just like for the saved html version of the report.

### Additional Information

```
R version 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

**Comment by SabrinaJaye** [comment]
Doing some light experimentation, I think this has something to do with when or where `$('.ui.accordion').accordion();` is triggered, as the save html report seems to work, and the js function that does `$('.ui.accordion').accordion();` is registered using htmlwidgets function that looks like it is triggered when static render is complete. And maaaybe this doesen't happen with uiOutputs?

If I open browser console and enter `$('.ui.accordion').accordion();` manually then hey presto the whole thing springs to life.

So I thought I'd try a hacky workaround that just listens to the #validate element of the example's html:

 ```
 $(function() {
  const targetNode = document.getElementById("validation");
  const config = { attributes: true, childList: true, subtree: true };
  const callback = (mutationList, observer) => {
    console.log("Stuff updated");
    console.log("running accordion");
    $(".ui.accordion").accordion();
  };
  const observer = new MutationObserver(callback);
  observer.observe(targetNode, config);
});
```

And this kiiiinda works, well, at first the accordion is dead, BUT once I click to expand details of one of the example errors, it springs to life.

It looks like the solution is to schedule the accodion function to be executed on the element whenever renderUI is done with it's thing? But I'm not 100% sure on how to do that in the JS, my attempts, like above, fall a bit short of a full workaround.

**Comment by SabrinaJaye** [comment]
I thought Shiny events might help.

```
$('#validation').on('shiny:value', function(event) {
    $("#validation .ui.styled.accordion:first").accordion();
  });
```

But no, the console just says `.accordion()` is not a function.

**Comment by jakubnowicki** [comment]
@SabrinaJaye thank you for reporting this. The issue has been fixed in the development version (available on GitHub). The fix is going to be included in the next CRAN release (planned for this quarter).
