### ISSUE TITLE
[Bug]: app crashes after 'show' on render_semantic_report_ui

### ISSUE THREAD

**Issue by dannyvolkaerts** [Appsilon/data.validator#52]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

4.1.2

### Platform and OS Version

Windows

### What happened?

After updating a tremendous number of packages (xfun,vctrs,..) in R-4.1.2 the data.validator package is not working in shiny (shiny version 1.7.1). The report variable is created correct but as soon as I ask in shiny to "show" the errors, the shiny app crashes without warning or error message in console.. No idea how to tackle it

### Steps to reproduce

1. Easy: I just tried to run the shiny example on the data.validator github page
2.
3.

### Expected behavior

to show the errors according to the validation rules I set

**Comment by jakubnowicki** [comment]
@dannyvolkaerts, the most probable is that the problem was related to an issue with CDN that serves `shiny.semantic` assets. Please check again - it should work now.

**Comment by dannyvolkaerts** [comment]
@jakubnowicki Thank you for the fast reply. The application indeed works now for the 'show' feature. However I cannot expand or close the 'Failed' or 'Passed' rules tab (don't know if it worked before).

**Comment by jakubnowicki** [comment]
@dannyvolkaerts this bug is already fixed in the development version available on GitHub. We plan to release it on CRAN within a month.

**Comment by dannyvolkaerts** [comment]
Super! Thank you very much! Case closed.

**Comment by dannyvolkaerts** [comment]
CDN issue - package works fine.
