### ISSUE TITLE
[Bug]: Unexpected NULL return in `data-name` attribute when using `%>%` operator with 'validate()' function 

### ISSUE THREAD

**Issue by ttnsy** [Appsilon/data.validator#61]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

0.2.0

### Platform and OS Version

macOs 13.3.1

### What happened?

When `name` argument is not provided, the function should return the name of `data` object as `data-name` attribute. This functionality works as expected when using either `validate(data)` or `data |> validate()`. However, when attempting to use `%>%` operator, the function returns NULL instead of the expected data name.

### Steps to reproduce

```{r}
library(data.validator)
library(dplyr)

data <- data.frame(V1 = c(0,1,2), V2 = c(3,4,5))
data_val <- validate(data)
```

First two examples returning name of the data object:

```{r}
# This works as expected
> attr(validate(data_val), "data-name")
[1] "data_val"
>
# This also works as expected
> data_val |>
+     validate() |>
+     attr("data-name")
[1] "data_val"
```

`NULL` return when using `%>%`:

```
> data_val %>%
+     validate() %>%
+     attr("data-name")
[1] "NULL"
```
### Expected behavior

When using the `%>%` operator with the `validate()` function, it should return the correct `data-name` attribute, similar to the other valid usage examples mentioned above.

### Attachments

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.3.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] assertr_3.0.0        dplyr_1.0.8          data.validator_0.2.0
```

**Comment by svalvaro** [comment]
This is a very interesting issue and complex issue. The current implementation stopped working after updates in `magrittr`. I have started working on a solution. Based on [this](https://stackoverflow.com/questions/52066097/get-expression-that-evaluated-to-dot-in-function-called-by-magrittr-pipe/52080518#52080518). 

 [Here](https://github.com/Appsilon/data.validator/tree/fix/61-unexpected-Null) is my work so far.

I also found some cases where the `|>` doesn't work as expected either. This branch should cover this situations:
```
  test_1 <- validate(data)
  test_2 <- data |> validate()
  test_3 <- data |> dplyr::select(V1) |> validate()
  test_4 <- data %>% validate()
  test_5 <- data %>% dplyr::select(V1) %>% validate()

  expect_equal(attr(test_1, "data-name"), "data")
  expect_equal(attr(test_2, "data-name"), "data")
  expect_equal(attr(test_3, "data-name"), "data")
  expect_equal(attr(test_4, "data-name"), "data")
  expect_equal(attr(test_5, "data-name"), "data")
```

Right now, the ones with the addition o `select` are the ones not fixed yet.
