### ISSUE TITLE
The package not compatible with assertr

### ISSUE THREAD

**Issue by rajkboddu** [Appsilon/data.validator#9]
the description parameter to the assert function is not available in [assertr ](https://github.com/ropensci/assertr)package - throws errors
the chain_start does not support any parameters.

the data.validator packaged depends on these things.

**Comment by FrieseWoudloper** [comment]
The errors are probably caused by this issue with `assertr`: https://github.com/ropensci/assertr/issues/96
Possible solution:
```
remove.packages("assertr")
remotes::install_github("ropensci/assertr")
```

**Comment by dokato** [comment]
Thanks, guys for pointing that out, indeed we don't really know what happens with `assertr`ATM (which is an excellent package BTW). @krystian8207 added quite a lot of changes there that were approved and merged in to master (and we rely on this version here), but later, to our surprise,`assertr` teamed pushed to CRAN some different version. See also: https://github.com/ropensci/assertr/issues/101  🤔 

So as @FrieseWoudloper suggested please use GitHub version for now.

**Comment by FrieseWoudloper** [comment]
Kudos to @tonyfischetti for fixing this issue by pushing assertr 2.8 to CRAN (https://github.com/ropensci/assertr/issues/96). This issue is solved and can be closed.

**Comment by tonyfischetti** [comment]
Y'all should be fine now :)

**Comment by krystian8207** [comment]
Closing the issue now due to new release of assertr. Thank you @tonyfischetti :)
